CREATE USER IF NOT EXISTS '${ADMIN_USER}'@'localhost' IDENTIFIED BY '${ADMIN_PASSWORD}';
GRANT ALL PRIVILEGES ON avion_papier.* TO '${ADMIN_USER}'@'localhost';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS '${READONLY_USER}'@'localhost' IDENTIFIED BY '${READONLY_PASSWORD}';
GRANT SELECT ON avion_papier.* TO '${READONLY_USER}'@'localhost';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS '${ORDER_USER}'@'localhost' IDENTIFIED BY '${ORDER_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE ON avion_papier.commandes TO '${ORDER_USER}'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON avion_papier.lignes_commandes TO '${ORDER_USER}'@'localhost';
FLUSH PRIVILEGES;

CREATE USER IF NOT EXISTS '${MANAGER_USER}'@'localhost' IDENTIFIED BY '${MANAGER_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE ON avion_papier.* TO '${MANAGER_USER}'@'localhost';  
FLUSH PRIVILEGES;
